### ISSUE TITLE
Add background so I don't feel like I'm in a blizzard

### ISSUE THREAD

**Issue by Thomas-Stewart** [ericjaychi/tic-tac-toe#12]
May I suggest this instead:

![screenshot from 2017-06-09 15-03-58](https://user-images.githubusercontent.com/10453406/28596491-a2bf891c-714d-11e7-9637-baeda94b6c74.png)

**Comment by ericjaychi** [comment]
Will take this into consideration, possibly will implement for first iteration since there was no plan for a background.

**Comment by ericjaychi** [comment]
Add Easter Egg button that allows this background to show.

**Comment by ericjaychi** [comment]
Moved to #23
